name: pytorch_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch-cuda=11.8
  - numpy
  - matplotlib
  - scikit-learn
  - pip
  - pip:
      - ipykernel
      - kaggle
